In [1]:
pip install -U fortran-magic

In [2]:
%reload_ext fortranmagic

/usr/local/lib/python3.6/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


In [3]:
%matplotlib  inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

The fortranmagic extension is already loaded. To reload it, use:
  %reload_ext fortranmagic


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [4]:
assert ran_the_first_cell, "Oh noes!"

In [5]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [6]:
l_2 = [7.0, 8.0, 'nine', 10.0, 11.0]
l_2

[7.0, 8.0, 'nine', 10.0, 11.0]

In [7]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [8]:
first = l_2[0]
second = l_2[1]
print("first:", first)
print("second:", second)

first: 7.0
second: 8.0


In [9]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [10]:
m=1
last = l_2[m-1]
penultimate = l_2[m-2]
print("Celda m-1:", last)
print("Celda m-2:", penultimate)

Celda m-1: 7.0
Celda m-2: 11.0


In [11]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [12]:
sublist = l_2[0:3]
sublist

[7.0, 8.0, 'nine']

In [13]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [14]:
Primero_Cuarto = l_2[:4]
Primero_Cuarto

[7.0, 8.0, 'nine', 10.0]

In [15]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [16]:
#Despues del 2
Despues_dos = l_2[2:]
Despues_dos 

['nine', 10.0, 11.0]

In [17]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [18]:
#Pasos de 3
l_3 = ['e','r', 't', 'y', 'u', 'i', 'o', 'p']
l_3[1:8:3]

['r', 'u', 'p']

In [19]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [20]:
#Forma bonita de invertir la lista
l_3[::-1]

['p', 'o', 'i', 'u', 'y', 't', 'r', 'e']

In [21]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [22]:
#insertando datos a la lista
l_4 = ['one', 2, 3, 'si', 5]
print("Before:", l_4)
l_4.append('no')
print("After:", l_4)

Before: ['one', 2, 3, 'si', 5]
After: ['one', 2, 3, 'si', 5, 'no']


In [23]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

In [24]:
#Redondeo
nums = [1.1,2.2,3.3,4.4,5.5]
[round(i) for i in nums]

[1, 2, 3, 4, 6]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [25]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

In [26]:
Einstein_data = {'name':'Albert', 'last-name':'Einstein', 'born-date':'14/03/1879', 'death-age':76}
Einstein_data

{'born-date': '14/03/1879',
 'death-age': 76,
 'last-name': 'Einstein',
 'name': 'Albert'}

In [27]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

In [28]:
#Al igual que lás listas, son de tamaño Variable

Einstein_data['nationality'] = 'Germany'
Einstein_data

{'born-date': '14/03/1879',
 'death-age': 76,
 'last-name': 'Einstein',
 'name': 'Albert',
 'nationality': 'Germany'}

In [29]:
del philosophers['David']
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

In [30]:
del Einstein_data['born-date']
Einstein_data

{'death-age': 76,
 'last-name': 'Einstein',
 'name': 'Albert',
 'nationality': 'Germany'}

In [31]:
# No slicing.
#philosophers['Bertrand':'Immanuel']

In [32]:
#Einstein_data[::-1]

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [33]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [34]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

In [35]:
def matadd(A,B):
    '''Adding matrix A and B'''
    if len(A) == len(B) and len(A[0]) == len(B[0]):
        C = [[0 for j in range(len(A[0]))] for i in range(len(A))]
        for i in range(len(A)):
            for j in range(len(A[0])):
                C[i][j] = A[i][j]+B[i][j]

        return C
    else:
        return False

<center><img src="images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [36]:
%%time

matmul(a, b)

CPU times: user 26 µs, sys: 6 µs, total: 32 µs
Wall time: 36 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

In [37]:
D = [[7, 4, 1],
     [8, 5, 2],
     [9, 6, 3],
     [7, 5, 3]]

In [38]:
%%time
matadd(b,D)

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 9.06 µs


False

In [39]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.21423451115786474, 0.6079294385704934, 0.815956068356173],
 [0.10484767724708766, 0.6513211294730215, 0.11468528329992345]]

In [40]:
def random_Me_matrix(m,n,lim):
    A = [[random.random()*lim for i in range(n)] for j in range(m)]

    return A

rnd_mat = random_Me_matrix(4,4,100)
rnd_mat

[[85.98131923016071, 83.88061579108843, 10.369515623473236, 77.84753586084516],
 [52.73287225071871,
  23.468970403567923,
  73.47123548583923,
  5.1814241857931815],
 [24.62560833492252, 8.033397438087853, 17.806091917711143, 16.76948924794607],
 [27.999673048135776, 3.89649386577281, 52.73827461648845, 42.63881136041735]]

In [41]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 5.63 s, sys: 12.5 ms, total: 5.64 s
Wall time: 5.66 s


In [42]:
%%time
rnd_a1 = random_Me_matrix(600, 100, 100)
rnd_b1 = random_Me_matrix(100, 600, 100)
x = matmul(rnd_a1, rnd_b1)

CPU times: user 5.6 s, sys: 16.7 ms, total: 5.61 s
Wall time: 5.62 s


In [43]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [44]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

In [45]:
def python_cross_product(a,b):
    return [a[1]*b[2] - a[2]*b[1], a[2]*b[0] - a[0]*b[2], a[0]*b[1] - a[1]*b[0]]

In [46]:
%%fortran
subroutine fortran_cross_product(a, b, cross)
    double precision, intent(in) :: a(:)
    double precision, intent(in) :: b(:)
    double precision, dimension(3), intent(out) :: cross

    cross(1) = a(2) * b(3) - a(3) * b(2)
    cross(2) = a(3) * b(1) - a(1) * b(3)
    cross(3) = a(1) * b(2) - a(2) * b(1)
end

In [47]:
list_data = [float(i) for i in range(50)]
array_data = np.array(list_data)

array_data

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [48]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 11 µs, sys: 1 µs, total: 12 µs
Wall time: 13.8 µs


40425.0

In [49]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 29 µs, sys: 0 ns, total: 29 µs
Wall time: 32.7 µs


40425.0

In [50]:
M_a = [np.array([random.random()*10 for i in range(4)]) for j in range(100)]
M_b = [np.array([random.random()*10 for i in range(4)]) for j in range(100)]

<center><img src="images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [51]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [52]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [53]:
import numpy as np
import random

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [54]:
data1 = np.array([11, 6, 3, 8])


In [55]:
data + data

array([2, 4, 6, 8])

In [56]:
data1*2

array([22, 12,  6, 16])

In [57]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 77 µs, sys: 2 µs, total: 79 µs
Wall time: 84.9 µs


40425.0

In [58]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 37 µs, sys: 0 ns, total: 37 µs
Wall time: 41 µs


40425.0

In [59]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 9 µs, sys: 0 ns, total: 9 µs
Wall time: 12.9 µs


40425.0

In [60]:
# Numpy won't allow us to write a string into an int array.
#data[0] = "foo"

In [61]:
#data1[0] = [1,2]

In [62]:
# We also can't grow an array once it's created.
#data.append(3)

In [63]:
#data1.remove(-1)

In [64]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

In [65]:
two_by_two = data1.reshape(2,2)
two_by_two

array([[11,  6],
       [ 3,  8]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [66]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


In [67]:
yo_arr = np.array(list(range(20,0,-1)),dtype='int8').reshape(2,10)
print("yo array:\n", yo_arr, sep='')
print("===========")
print("DType:", yo_arr.dtype)
print("Shape:", yo_arr.shape)
print("Strides:", yo_arr.strides)
print("Data:", yo_arr.data.tobytes())

yo array:
[[20 19 18 17 16 15 14 13 12 11]
 [10  9  8  7  6  5  4  3  2  1]]
DType: int8
Shape: (2, 10)
Strides: (10, 1)
Data: b'\x14\x13\x12\x11\x10\x0f\x0e\r\x0c\x0b\n\t\x08\x07\x06\x05\x04\x03\x02\x01'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [68]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:

data2 = np.arange(20,0,-1,dtype=float).reshape(2, 10)
np.sqrt(data2)

array([[4.47213595, 4.35889894, 4.24264069, 4.12310563, 4.        ,
        3.87298335, 3.74165739, 3.60555128, 3.46410162, 3.31662479],
       [3.16227766, 3.        , 2.82842712, 2.64575131, 2.44948974,
        2.23606798, 2.        , 1.73205081, 1.41421356, 1.        ]])

In [70]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [71]:
data2/data2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [73]:
np.product(data2)

2.43290200817664e+18

In [74]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [75]:
((data2 % 2) == 0) * ((data2 % 3) == 0)

array([[False, False,  True, False, False, False, False, False,  True,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False]])

In [76]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [77]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [78]:
np.log(data2 @ (2*data2.T))

array([[8.51117512, 7.53369371],
       [7.53369371, 6.64639051]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [79]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [80]:
Me2_sines = np.sin(np.arange(0,15.707,1.5707))
Me2_cosines = np.cos(np.arange(0,15.707,1.5707))
np.round(Me2_sines)

array([ 0.,  1.,  0., -1., -0.,  1.,  0., -1., -0.,  1.])

In [81]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

In [82]:
Me2_cosines[0:5]


array([ 1.00000000e+00,  9.63267947e-05, -9.99999981e-01, -2.88980381e-04,
        9.99999926e-01])

In [83]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

In [84]:
np.round(Me2_cosines[:len(Me2_cosines)//2])

array([ 1.,  0., -1., -0.,  1.])

In [85]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [86]:
Me2_cosines[len(Me2_cosines)//2:]

array([ 4.81633956e-04, -9.99999833e-01, -6.74287513e-04,  9.99999703e-01,
        8.66941045e-04])

In [87]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [88]:
print('ME cosines', np.round(Me2_cosines[::2])) 

ME cosines [ 1. -1.  1. -1.  1.]


In [89]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [90]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [91]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [92]:
Me_data = np.array([random.randint(-10,10) for i in range(10)])
Me_data

array([ 0,  8, -9, -5, -6, -4,  3, -5, -3, -8])

In [93]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [94]:
Me_sort_indices = np.argsort(Me_data)
Me_sort_indices

array([2, 9, 4, 3, 7, 5, 8, 0, 6, 1])

In [95]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [96]:
Me_data[Me_sort_indices]

array([-9, -8, -6, -5, -5, -4, -3,  0,  3,  8])

In [97]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [98]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [99]:
jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

In [100]:
aug2020 = pd.to_datetime(['2020-08-03 00:00:00+00:00',
'2020-08-04 00:00:00+00:00',
'2020-08-05 00:00:00+00:00',
'2020-08-06 00:00:00+00:00',
'2020-08-09 00:00:00+00:00',
'2020-08-10 00:00:00+00:00',
'2020-08-11 00:00:00+00:00',
'2020-08-12 00:00:00+00:00',
'2020-08-13 00:00:00+00:00',
'2020-08-17 00:00:00+00:00',
'2020-08-18 00:00:00+00:00',
'2020-08-19 00:00:00+00:00',
'2020-08-20 00:00:00+00:00',
'2020-08-23 00:00:00+00:00',
'2020-08-24 00:00:00+00:00',
'2020-08-25 00:00:00+00:00',
'2020-08-26 00:00:00+00:00',
'2020-08-27 00:00:00+00:00',
'2020-08-30 00:00:00+00:00',
'2020-08-31 00:00:00+00:00'])

Me_calendar = aug2020.values.astype('datetime64[D]')

Me_event = pd.to_datetime(['2020-08-17 00:00:00+00:00', 
                             '2020-08-18 00:00:00+00:00', 
                             '2020-08-19 00:00:00+00:00']).values.astype('datetime64[D]')
Me_event_values = np.array([16, 13, 14])

In [101]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [102]:
print("Dates:\n", repr(Me_event))
print("Values:\n", repr(Me_event_values))
print("Calendar:\n", repr(Me_calendar))

Dates:
 array(['2020-08-17', '2020-08-18', '2020-08-19'], dtype='datetime64[D]')
Values:
 array([16, 13, 14])
Calendar:
 array(['2020-08-03', '2020-08-04', '2020-08-05', '2020-08-06',
       '2020-08-09', '2020-08-10', '2020-08-11', '2020-08-12',
       '2020-08-13', '2020-08-17', '2020-08-18', '2020-08-19',
       '2020-08-20', '2020-08-23', '2020-08-24', '2020-08-25',
       '2020-08-26', '2020-08-27', '2020-08-30', '2020-08-31'],
      dtype='datetime64[D]')


In [103]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [104]:
print("Raw Dates:", Me_event)
print("Indices:", Me_calendar.searchsorted(Me_event))
print("Forward-Filled Dates:", Me_calendar[Me_calendar.searchsorted(Me_event)])

Raw Dates: ['2020-08-17' '2020-08-18' '2020-08-19']
Indices: [ 9 10 11]
Forward-Filled Dates: ['2020-08-17' '2020-08-18' '2020-08-19']


In [105]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [106]:
data4 = np.arange(16).reshape(4, 4)
data4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [107]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

In [108]:
data4[:3, :3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [109]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [110]:
data4[:,list(range(0,len(data4[0]),2))]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [111]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [112]:
data4[((data4 % 2) == 0) * ((data4 % 3) == 0)] 

array([ 0,  6, 12])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [113]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [114]:
def my_std(x):
    return np.sqrt(((x - x.mean()) ** 2).sum() / (len(x)-1))

In [115]:
variance(np.random.standard_normal(1000))

1.0014043049274388

In [116]:
my_std(np.random.standard_normal(1000))

1.0007733192343615

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [117]:
data = np.arange(30)
data.mean()

14.5

In [118]:
data5 = np.arange(-10,10)
data5.mean()

-0.5

- ...but we can do more interesting things with multi-dimensional arrays.

In [119]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [120]:
data5 = np.arange(-10,10).reshape(5,4)
data5

array([[-10,  -9,  -8,  -7],
       [ -6,  -5,  -4,  -3],
       [ -2,  -1,   0,   1],
       [  2,   3,   4,   5],
       [  6,   7,   8,   9]])

In [121]:
data.mean()

14.5

In [122]:
data5.mean()

-0.5

In [123]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [124]:
data5.mean(axis=0)

array([-2., -1.,  0.,  1.])

In [125]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

In [126]:
data5.mean(axis=1)

array([-8.5, -4.5, -0.5,  3.5,  7.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [127]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [128]:
Me_row = np.array([5, 6, 7, 8])
Me_column = np.array([[1], [2], [3], [4]])
print("Row:\n", Me_row, sep='')
print("Column:\n", Me_column, sep='')

Row:
[5 6 7 8]
Column:
[[1]
 [2]
 [3]
 [4]]


In [129]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [130]:
Me_row * Me_column

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

<center><img src="images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [131]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


In [132]:
print("Data:\n", Me_data, sep='')
print("Mean:\n", Me_data.mean(), sep='')
print("Data - Mean:\n", Me_data - Me_data.mean(), sep='')

Data:
[ 0  8 -9 -5 -6 -4  3 -5 -3 -8]
Mean:
-2.9
Data - Mean:
[ 2.9 10.9 -6.1 -2.1 -3.1 -1.1  5.9 -2.1 -0.1 -5.1]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [133]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [134]:
s2 = pd.Series(index=['one','two','three','four','five','six'], data=[1,2,3,5,8,13],dtype='int16')
s2

one       1
two       2
three     3
four      5
five      8
six      13
dtype: int16

In [135]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


In [136]:

print("The index is:", s2.index)
print("The values are:", s2.values)

The index is: Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')
The values are: [ 1  2  3  5  8 13]


In [137]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [138]:
s2.iloc[-3]

5

In [139]:
# ... or by label.
s.loc['a']

1

In [140]:
s2.loc['four']

5

In [141]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [142]:
s2.iloc[-3:]

four     5
five     8
six     13
dtype: int16

In [143]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [144]:
s2.loc['three':]

three     3
four      5
five      8
six      13
dtype: int16

In [145]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [146]:
s2[[0,2,-2,-4]]

one      1
three    3
five     8
three    3
dtype: int16

In [147]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [148]:
s2[s2 % 2 == 0]

two     2
five    8
dtype: int16

In [149]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [150]:
other_s2 = pd.Series({'one': 1, 'two': 4, 'three': 9, 'four': 16, 'five': 25, 'six': 36})
other_s2

one       1
two       4
three     9
four     16
five     25
six      36
dtype: int64

In [151]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [152]:
s2 * other_s2

one        1
two        8
three     27
four      80
five     200
six      468
dtype: int64

In [153]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [155]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

FileNotFoundError: ignored

In [ ]:
msft = pd.read_csv('MSFT.csv', parse_dates=['date'], index_col='date')
msft.head()

In [ ]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

In [ ]:

msft.iloc[-10:,:3]

In [ ]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

# Rolling Operations

<center><img src="images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [ ]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

In [ ]:
msft.rolling(3)[['high', 'price', 'low']].mean().plot();

In [ ]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

In [ ]:
msft.drop('volume', axis=1).resample('3D').max().plot();

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

In [ ]:
msft['price'].pct_change().plot();

# "Real World" Data

In [ ]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

In [ ]:
read_avocadata('2015','2015').head()

In [ ]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

In [ ]:
avocados.dtypes[:3]

In [ ]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
avocados

In [ ]:
greenskin = avocados[avocados.Variety == 'GREENSKIN']
greenskin.groupby(['Date','Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [ ]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
organic_spread_by_region(greenskin).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

In [ ]:
my_spread_correlation = organic_spread_by_region(greenskin).corr()
my_spread_correlation

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

In [ ]:
my_grid = sns.clustermap(my_spread_correlation[1:].dropna(axis=1), annot=True)
my_fig = my_grid.fig
my_axes = my_fig.axes
my_ax = my_axes[2]
my_ax.set_xticklabels(my_ax.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!